# Generated by Django 5.1.1 on 2024-10-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
