# Generated by Django 5.1.1 on 2024-11-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_delete_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorData',
        ),
    ]
