# Generated by Django 5.1.1 on 2024-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
