# Generated by Django 5.1.1 on 2024-11-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0016_alter_temperaturedata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredservice',
            name='device_id',
        ),
    ]
