# Generated by Django 5.1.1 on 2024-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0020_remove_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_duration',
            field=models.IntegerField(),
        ),
    ]
