# Generated by Django 5.1.1 on 2024-11-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0021_alter_subscription_subscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='interval_between_readings',
            field=models.FloatField(),
        ),
    ]
